[package]
name = "snarkyed"
version = "0.1.0"
authors = ["Huy Tran <kingbazoka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.25.1"
glium-glyph = "0.6.0"
glyph_brush = "0.5"
ropey = "1.1.0"
